apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: &app nginx
    version: &version nginx:1.27.5
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: *app
      version: *version
  template:
    metadata:
      name: first-pod
      namespace: work
      labels:
        app: *app
        version: *version
    spec:
      initConteiners:
        - name: init-service
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - 'echo Initializing... && sleep 10'
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"      
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10    